#!/usr/bin/env python3
import sys

def create_cpp(x):
    command = '#include <bits/stdc++.h> \nusing namespace std; \nint main() { \nsystem("clear"); \nreturn 0;'

    for x in range(x):
        with open(f"Zad{x+1}.cpp", "w") as f:
            f.write(command)

def create_py(x):
    command = "import os\nos.system('clear')"

    for x in range(x):
        with open(f"Zad{x+1}.py", "w") as f:
            f.write(command)

type_of_file = sys.argv[1]
num_of_files = int(sys.argv[2])

if type_of_file == "cpp":
    create_cpp(num_of_files)
elif type_of_file == "py":
    create_py(num_of_files)
else:
    print("Wrong file type\n")

