#!/usr/bin/env python3
import sys



def create_cpp(num_of_files, name_of_files):
    command = '#include <iostream>\n\nint main() {\n\n\treturn 0;\n}'

    for num_of_files in range(num_of_files):
        with open(f"{name_of_files}{num_of_files+1}.cpp", "w") as f:
            f.write(command)


def create_py(x, name_of_files):
    command = "#!/usr/bin/env python3\nimport os\n\ndef main():\n   os.system('clear')\n\nif __name__ == '__main__':\n  main()"

    for x in range(x):
        with open(f"{name_of_files}{x+1}.py", "w") as f:
            f.write(command)


type_of_files = sys.argv[1]
num_of_files = int(sys.argv[2])
name_of_files = sys.argv[3]


def main():
    if type_of_files == "cpp":
        create_cpp(num_of_files, name_of_files)
    elif type_of_files == "py":
        create_py(num_of_files, name_of_files)
    else:
        print("Wrong file type\n")


if __name__ == "__main__":
    main()
