#!/usr/bin/env bash

FILES_NAME="test_file"

if [[ ! -d test ]]; then
    mkdir test
fi

# Create test files
files_create cpp 4 test/"${FILES_NAME}"

function test_loop() {
    for i in {1..4}
    do
        sleep 1; sed -i '5 i\std::cout << "Test 1" << std::endl;' test/"$FILES_NAME""$i".cpp
    done
    
    # i=2
    # while [[ ! $i -eq 5 ]]; do
    #     sed -i "s/Test [0-9]*/Test $i/" test/"$FILES_NAME"*.cpp
    #     sleep 5
    #     (( i++ ))
    # done
    
    rm -r test
}

test_loop